### ISSUE TITLE
Allow downloading of Run measurements

### ISSUE THREAD

**Issue by Panaetius** [mlbench/mlbench#35]
All the metrics of a run should be downloadable as a CSV

**Comment by LiamHe** [comment]
I have added some code to allow downloading metrics as a json file in `feature/download_results`. Each metric corresponds to one entry in the json. If we want to save the metrics in csv format, we may need save them into multiple files. The following choices are not that different, but which one you think we should use for now ?

- Download as one json for all metrics, leave the conversion to the user;
- Download multiple csv files for all metrics;
- Download a specific metric in csv format (one button for each metric tab);
- something else?

**Comment by Panaetius** [comment]
Oh I'm currently working on a method that downloads everything for a run as a single zip

**Comment by martinjaggi** [comment]
thanks guys!
this is nice but priority-wise we could also move it to v0.2
