### ISSUE TITLE
Check mlbench works on Google Cloud

### ISSUE THREAD

**Issue by Panaetius** [mlbench/mlbench#51]

**Comment by Panaetius** [comment]
Everyhing works, installation docs updated accordingly

**Comment by martinjaggi** [comment]
nice! did you commit the installation docs?

**Comment by Panaetius** [comment]
Yes, here: https://github.com/mlbench/mlbench/blob/refactor/controlflow/docs/installation.rst

Note: ReadTheDocs formatting looks a lot nicer, a large part of the guide is how to host your own image in googles docker registry, but Note's are not formatted nicely with github's .rst parser, so the guide for a default install is less than 50% of all the instructions there. I.e. if you look at it on github, it looks way more complicated at a first glance than it actually is.
