### ISSUE TITLE
small doc improvements for first release

### ISSUE THREAD

**Issue by martinjaggi** [mlbench/mlbench#54]
* in docs/installation.rst 

  * let's add some more comments on the underlying system, for example a cluster, what rights are needed. be clear helm needs to be on laptop of cluster and precise installation command.

  * where to install mlbench chart

  * mention what limits are for (just for the GUI), what if they are larger than physical limits. and reorder them as
```
limits:
  maximumWorkers:
  cpu:
  bandwidth:
```

* overview: should be renamed to sth else. maybe technical overview? 
  * make REST API a subsection of that

**Comment by Panaetius** [comment]
I redid most of the documentation pages to make it cleaner and more succint

**Comment by martinjaggi** [comment]
thanks, looks good
